inputs:
  dir:
    description: folder path (relative to root)
    required: true

runs:
  using: composite
  steps:      
    - run: |
        import os
        DIR = os.path.abspath(os.path.join(os.getcwd(), os.path.normpath(os.environ['IPT_DIR'])))
        print(DIR)
      shell: python
      env:
        IPT_DIR: ${{ inputs.dir }}
